### ISSUE TITLE
Request not send to origin when using docker-compose

### ISSUE THREAD

**Issue by n0b0dyCN** [akamai/esi-test-server-docker#9]
Hi, I arrange my folder as following:
```
├── docker-compose.yml
├── html
│   ├── akamai-logo.png
│   ├── geo.html
│   ├── gzip.html
│   ├── index.html
│   ├── sample.html
│   ├── style.css
│   ├── test.txt
│   └── version.txt
└── nginx-gzip
    └── Dockerfile
```
And my `docker-compose.yml`:
```
version: '2' # older version for broader compat
services:
  ets:
    image: "akamaiesi/ets-docker:latest"
    environment:
        - ETS_CLI_ARGS=--remote_origin origin:9001 --debug origin
    links:
      - origin
    ports:
        - "9000:80"
  origin:
    build: nginx-gzip
    image: "nginx-gzip"
    ports:
        - "127.0.0.1:9001:80"
    volumes:
      - ./html:/usr/share/nginx/html
```
When I run `docker-compose up` and visit `127.0.0.1:9000/geo.html`, I got a 404 error and seems that the request is not passed to nginx docker. Do I make any mistakes when I use the docker?
